name: Design
highlighter: pygments
relative_permalinks: false
baseurl: /design
permalink: pretty
exclude: [scss, node_modules, bower.json, Gruntfile.js, package.json, README.md]
markdown: kramdown
sass:
  load_paths:
    - _sass
    - node_modules/pearson-elements/scss
sections:
  - Components
gems:
  - jekyll-redirect-from
