name: Design
highlighter: rouge
relative_permalinks: false
baseurl: /design
permalink: pretty
exclude: [scss, node_modules, bower.json, Gruntfile.js, package.json, README.md]
markdown: kramdown
sections:
  - Components
gems:
  - jekyll-redirect-from
