name: Pearson UX Framework
highlighter: rouge
relative_permalinks: false
url: http://uxframework.pearson.com
permalink: pretty
exclude: [scss, bower.json, Gruntfile.js, package.json, README.md]
markdown: kramdown
sections:
  - Components
gems:
  - jekyll-redirect-from
kramdown:
  toc_levels: '2'
include: [node_modules]
